# Generated by Django 5.0.4 on 2024-04-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="review",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="watched",
            field=models.BooleanField(default=False),
        ),
    ]
