# Generated by Django 5.0.4 on 2024-05-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0005_seenlist_watchlist_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='seenlist',
            name='overview',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='overview',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='poster_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
